/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiciosIndexRouteImport } from './routes/servicios.index'
import { Route as ServiciosWebsitesRouteImport } from './routes/servicios.websites'
import { Route as ServiciosMarketingRouteImport } from './routes/servicios.marketing'

const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosIndexRoute = ServiciosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiciosRoute,
} as any)
const ServiciosWebsitesRoute = ServiciosWebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => ServiciosRoute,
} as any)
const ServiciosMarketingRoute = ServiciosMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => ServiciosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/servicios/marketing': typeof ServiciosMarketingRoute
  '/servicios/websites': typeof ServiciosWebsitesRoute
  '/servicios/': typeof ServiciosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/servicios/marketing': typeof ServiciosMarketingRoute
  '/servicios/websites': typeof ServiciosWebsitesRoute
  '/servicios': typeof ServiciosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/servicios/marketing': typeof ServiciosMarketingRoute
  '/servicios/websites': typeof ServiciosWebsitesRoute
  '/servicios/': typeof ServiciosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/servicios'
    | '/servicios/marketing'
    | '/servicios/websites'
    | '/servicios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/servicios/marketing'
    | '/servicios/websites'
    | '/servicios'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/servicios'
    | '/servicios/marketing'
    | '/servicios/websites'
    | '/servicios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  ServiciosRoute: typeof ServiciosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/': {
      id: '/servicios/'
      path: '/'
      fullPath: '/servicios/'
      preLoaderRoute: typeof ServiciosIndexRouteImport
      parentRoute: typeof ServiciosRoute
    }
    '/servicios/websites': {
      id: '/servicios/websites'
      path: '/websites'
      fullPath: '/servicios/websites'
      preLoaderRoute: typeof ServiciosWebsitesRouteImport
      parentRoute: typeof ServiciosRoute
    }
    '/servicios/marketing': {
      id: '/servicios/marketing'
      path: '/marketing'
      fullPath: '/servicios/marketing'
      preLoaderRoute: typeof ServiciosMarketingRouteImport
      parentRoute: typeof ServiciosRoute
    }
  }
}

interface ServiciosRouteChildren {
  ServiciosMarketingRoute: typeof ServiciosMarketingRoute
  ServiciosWebsitesRoute: typeof ServiciosWebsitesRoute
  ServiciosIndexRoute: typeof ServiciosIndexRoute
}

const ServiciosRouteChildren: ServiciosRouteChildren = {
  ServiciosMarketingRoute: ServiciosMarketingRoute,
  ServiciosWebsitesRoute: ServiciosWebsitesRoute,
  ServiciosIndexRoute: ServiciosIndexRoute,
}

const ServiciosRouteWithChildren = ServiciosRoute._addFileChildren(
  ServiciosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  ServiciosRoute: ServiciosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
