/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiciosIndexRouteImport } from './routes/servicios.index'
import { Route as ServiciosWebsitesRouteImport } from './routes/servicios.websites'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosIndexRoute = ServiciosIndexRouteImport.update({
  id: '/servicios/',
  path: '/servicios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosWebsitesRoute = ServiciosWebsitesRouteImport.update({
  id: '/servicios/websites',
  path: '/servicios/websites',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/servicios/websites': typeof ServiciosWebsitesRoute
  '/servicios/': typeof ServiciosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/servicios/websites': typeof ServiciosWebsitesRoute
  '/servicios': typeof ServiciosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/servicios/websites': typeof ServiciosWebsitesRoute
  '/servicios/': typeof ServiciosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/servicios/websites' | '/servicios/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/servicios/websites' | '/servicios'
  id: '__root__' | '/' | '/servicios/websites' | '/servicios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServiciosWebsitesRoute: typeof ServiciosWebsitesRoute
  ServiciosIndexRoute: typeof ServiciosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/': {
      id: '/servicios/'
      path: '/servicios'
      fullPath: '/servicios/'
      preLoaderRoute: typeof ServiciosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/websites': {
      id: '/servicios/websites'
      path: '/servicios/websites'
      fullPath: '/servicios/websites'
      preLoaderRoute: typeof ServiciosWebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServiciosWebsitesRoute: ServiciosWebsitesRoute,
  ServiciosIndexRoute: ServiciosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
