/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ServiciosIndexRouteImport } from './routes/servicios.index'
import { Route as ServiciosMarketingRouteImport } from './routes/servicios.marketing'
import { Route as ServiciosVideoConDronRouteImport } from './routes/servicios.video-con-dron'
import { Route as ServiciosWebsitesRouteImport } from './routes/servicios.websites'
import { Route as ServiciosWhatsappIaRouteImport } from './routes/servicios.whatsapp-ia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosIndexRoute = ServiciosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiciosRoute,
} as any)
const ServiciosMarketingRoute = ServiciosMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => ServiciosRoute,
} as any)
const ServiciosVideoConDronRoute = ServiciosVideoConDronRouteImport.update({
  id: '/video-con-dron',
  path: '/video-con-dron',
  getParentRoute: () => ServiciosRoute,
} as any)
const ServiciosWebsitesRoute = ServiciosWebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => ServiciosRoute,
} as any)
const ServiciosWhatsappIaRoute = ServiciosWhatsappIaRouteImport.update({
  id: '/whatsapp-ia',
  path: '/whatsapp-ia',
  getParentRoute: () => ServiciosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/privacidad': typeof PrivacidadRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/servicios/marketing': typeof ServiciosMarketingRoute
  '/servicios/video-con-dron': typeof ServiciosVideoConDronRoute
  '/servicios/websites': typeof ServiciosWebsitesRoute
  '/servicios/whatsapp-ia': typeof ServiciosWhatsappIaRoute
  '/blog/': typeof BlogIndexRoute
  '/servicios/': typeof ServiciosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/privacidad': typeof PrivacidadRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/servicios/marketing': typeof ServiciosMarketingRoute
  '/servicios/video-con-dron': typeof ServiciosVideoConDronRoute
  '/servicios/websites': typeof ServiciosWebsitesRoute
  '/servicios/whatsapp-ia': typeof ServiciosWhatsappIaRoute
  '/blog': typeof BlogIndexRoute
  '/servicios': typeof ServiciosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/privacidad': typeof PrivacidadRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/servicios/marketing': typeof ServiciosMarketingRoute
  '/servicios/video-con-dron': typeof ServiciosVideoConDronRoute
  '/servicios/websites': typeof ServiciosWebsitesRoute
  '/servicios/whatsapp-ia': typeof ServiciosWhatsappIaRoute
  '/blog/': typeof BlogIndexRoute
  '/servicios/': typeof ServiciosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/privacidad'
    | '/servicios'
    | '/blog/$slug'
    | '/servicios/marketing'
    | '/servicios/video-con-dron'
    | '/servicios/websites'
    | '/servicios/whatsapp-ia'
    | '/blog/'
    | '/servicios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/privacidad'
    | '/blog/$slug'
    | '/servicios/marketing'
    | '/servicios/video-con-dron'
    | '/servicios/websites'
    | '/servicios/whatsapp-ia'
    | '/blog'
    | '/servicios'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/privacidad'
    | '/servicios'
    | '/blog/$slug'
    | '/servicios/marketing'
    | '/servicios/video-con-dron'
    | '/servicios/websites'
    | '/servicios/whatsapp-ia'
    | '/blog/'
    | '/servicios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ServiciosRoute: typeof ServiciosRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/': {
      id: '/servicios/'
      path: '/'
      fullPath: '/servicios/'
      preLoaderRoute: typeof ServiciosIndexRouteImport
      parentRoute: typeof ServiciosRoute
    }
    '/servicios/marketing': {
      id: '/servicios/marketing'
      path: '/marketing'
      fullPath: '/servicios/marketing'
      preLoaderRoute: typeof ServiciosMarketingRouteImport
      parentRoute: typeof ServiciosRoute
    }
    '/servicios/video-con-dron': {
      id: '/servicios/video-con-dron'
      path: '/video-con-dron'
      fullPath: '/servicios/video-con-dron'
      preLoaderRoute: typeof ServiciosVideoConDronRouteImport
      parentRoute: typeof ServiciosRoute
    }
    '/servicios/websites': {
      id: '/servicios/websites'
      path: '/websites'
      fullPath: '/servicios/websites'
      preLoaderRoute: typeof ServiciosWebsitesRouteImport
      parentRoute: typeof ServiciosRoute
    }
    '/servicios/whatsapp-ia': {
      id: '/servicios/whatsapp-ia'
      path: '/whatsapp-ia'
      fullPath: '/servicios/whatsapp-ia'
      preLoaderRoute: typeof ServiciosWhatsappIaRouteImport
      parentRoute: typeof ServiciosRoute
    }
  }
}

interface ServiciosRouteChildren {
  ServiciosMarketingRoute: typeof ServiciosMarketingRoute
  ServiciosVideoConDronRoute: typeof ServiciosVideoConDronRoute
  ServiciosWebsitesRoute: typeof ServiciosWebsitesRoute
  ServiciosWhatsappIaRoute: typeof ServiciosWhatsappIaRoute
  ServiciosIndexRoute: typeof ServiciosIndexRoute
}

const ServiciosRouteChildren: ServiciosRouteChildren = {
  ServiciosMarketingRoute: ServiciosMarketingRoute,
  ServiciosVideoConDronRoute: ServiciosVideoConDronRoute,
  ServiciosWebsitesRoute: ServiciosWebsitesRoute,
  ServiciosWhatsappIaRoute: ServiciosWhatsappIaRoute,
  ServiciosIndexRoute: ServiciosIndexRoute,
}

const ServiciosRouteWithChildren = ServiciosRoute._addFileChildren(
  ServiciosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  PrivacidadRoute: PrivacidadRoute,
  ServiciosRoute: ServiciosRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
